spring:
  datasource:
    url: jdbc:mysql://localhost:3306/alkemy_ong
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
    initialization-mode: always
    continue-on-error: true
    springdoc:
      api-docs:
        path=/api-docs: http://localhost:8080/api-docs/